# Generated by Django 4.1.7 on 2023-03-15 13:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.CharField(default=uuid.UUID('545a4009-9cf4-4a37-8caf-800823eb7429'), max_length=40, unique=True),
        ),
    ]
