# Generated by Django 4.1.7 on 2023-03-15 20:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_alter_company_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.CharField(default=uuid.UUID('972816d9-ad24-47fb-a3a6-41ae1d0be9a1'), max_length=40, unique=True),
        ),
    ]
