# Generated by Django 4.1.7 on 2023-03-15 13:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0002_alter_company_company_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Used', 'Used')], default='New', max_length=40)),
                ('check_in', models.DateTimeField(auto_now_add=True)),
                ('asset_id', models.CharField(default=uuid.UUID('d52fae6d-4ba8-4eb6-b6a8-90bc8dcd93f9'), max_length=100, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='Login.company')),
            ],
            options={
                'verbose_name_plural': 'Assets',
                'db_table': 'Assets',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=264)),
                ('middle_name', models.CharField(blank=True, max_length=264)),
                ('last_name', models.CharField(max_length=264)),
                ('address_1', models.TextField(blank=True, max_length=264)),
                ('city', models.CharField(blank=True, max_length=40)),
                ('zipcode', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(blank=True, max_length=40)),
                ('phone', models.CharField(max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('company_id', models.CharField(max_length=60)),
                ('employee_id', models.CharField(default=uuid.UUID('497d800b-5d08-403f-8bbb-734de9ab411d'), max_length=100, unique=True)),
                ('employee_company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_company', to='Login.company')),
            ],
            options={
                'verbose_name_plural': 'Employee',
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_condition', models.CharField(choices=[('New', 'New'), ('Used', 'Used')], default='Used', max_length=40)),
                ('return_date', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.assets')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.employee')),
            ],
            options={
                'verbose_name_plural': 'Delegation',
                'db_table': 'Delegation',
            },
        ),
    ]
