# Generated by Django 4.1.7 on 2023-03-15 20:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_alter_company_company_id'),
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='asset_id',
            field=models.CharField(default=uuid.UUID('fae05d49-b40e-48dd-be2f-99b728e445d1'), max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_company', to='Login.company'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(default=uuid.UUID('86672fbb-451d-4a26-a8a3-086977ddd530'), max_length=100, unique=True),
        ),
    ]
