# Generated by Django 4.1.7 on 2023-03-15 20:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_assets_asset_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='asset_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
